### ISSUE TITLE
Image flows to the right and disappears [Laptops with touchscreen]

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [rejas/imagelightbox#108]
**Steps to reproduce**

1.  Open incognito mode (no extensions)
2. Open imagelightbox demo page https://rejas.github.io/imagelightbox/
3. Open image in fullscreen
4. Move mouse
5. Image flows to the right and disappears

This bug seems to be happening only on laptops with touchscreen (tested 3 of them).

Can we expect a fix?

**Comment by rejas** [comment]
Question: How exactly do you move the mouse? And happens it with all demos on the page?

**Comment by RistoNiinemets** [comment]
This is a issue with Touch-enabled Windows devices (maybe laptops?). Also for me.

If I hover on any of the images, the image will pop right. After hovering again, it will disappear.

**Comment by ZilvinasKucinskas** [comment]
@rejas I just got a chance to try it out with touch screen computer today.

Summary:
1. Filter images by extension part of https://rejas.github.io/imagelightbox/ - It does not open, however it seems to not work on my normal laptop too.
2. All example images tries to escape the mouse. 
  a) When you click on an image and if mouse is not hovered over image - image stays at the center of the screen. Once you hover over the picture with mouse - it tries to escape and runs to the right.
  b) When you click on an image and mouse is already hovered over the image - image instantly runs to the right.

Touching the image on the screen (monitor) works ok.

**Comment by RistoNiinemets** [comment]
Well, my laptop does not have touchscreen, but the problem occoured. It has something to do with latest Google Chrome versions or Windows 10 updates.

I fixed my issue with this:
https://github.com/osvaldasvalutis/imageLightbox.js/issues/3#issuecomment-269925816

**Comment by rejas** [comment]
Could you both try out v0.7.2 i just realeased?

**Comment by ZilvinasKucinskas** [comment]
@rejas I don't personally have touch screen computer, but user reported that problem is solved with v0.7.2. 

Good job! Thank you.
