### ISSUE TITLE
"Next image" and "previous image" mapped incorrectly to arrows

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#109]
Is it just me, or are arrows incorrectly triggered next and previous image loading?

Clicking the right arrow should load the next image; however, it seems to be doing the opposite. This is probably a sign error or similar.

**Comment by rejas** [comment]
I cant see anything wrong when looking at the github.demo page or current master. The "arrow" example you mean?

**Comment by paxperscientiam** [comment]
@rejas Man, I don't know when I wrote that. Maybe I was dreaming it; site seems fine now.

I'll close.

**Comment by rejas** [comment]
True, I can reproduce that behaviour in Firefox Responsive Design Mode. But only there, neither Firefox for Android nor Chrome for Android shows this bug on my smartphone... Maybe related to issue #47 ?

**Comment by rejas** [comment]
The real problem wasn't that the arrow buttons were mapped incorrectly. Instead the "next" "prev" action was triggered twice, resulting in what looks like going from image2 to image1 but really going from image2 to image3 and then to image1.

**Comment by paxperscientiam** [comment]
That is curious. Glad you figured it out...something to learn from.
