### ISSUE TITLE
Double-tap (or, double-click) image for fullscreen

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#110]
@rejas I looked into the possibility of introducing fullscreen support via the Fullscreen API. I think it looks great. You?

What do you think about introducing this as feature?

The __easiest__ way would be to use a library like [screenful.js](https://github.com/sindresorhus/screenfull.js).

**Comment by rejas** [comment]
I like the idea. I am not sure if we need a third party library for that, screensful.js looks not that complicated. And caniuse seems to indicate that the fullscreen api is pretty got supported.

**Comment by paxperscientiam** [comment]
What is the proper way to cite someone's work?

I am using code from both [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) and (David Walsh)(https://davidwalsh.name/fullscreen).

I'll submit PR for you to see what I mean.

**Comment by rejas** [comment]
Not sure what you use from Mozilla but those few lines from David Walsh I think are not citeworthy, that's just common logic.
