### ISSUE TITLE
Compatibility with bootstrap

### ISSUE THREAD

**Issue by mspann** [rejas/imagelightbox#113]
When I include imagelightbox.min.js to my project, the collapse-Button of the Navigation-Bar created with bootstrap does not work anymore. Is this a known issue?

**Comment by rejas** [comment]
It isnt. Is there a site I can see that behaviour? Or can you look if error shows up in your brwoser console?

**Comment by mspann** [comment]
test.spannmacher.com
Either the bootstrap dropdown works or the lightbox - but never both.

**Comment by rejas** [comment]
Could you try to set quitOnDocClick option to false when initializing the imagelightbox?

**Comment by mspann** [comment]
Done. Unfortunately the issue persits.

**Comment by mspann** [comment]
I was able to narrow down the problem. It occurs when 
`<script>$( function() { 
$('a[data-imagelightbox="ufo"]').imageLightbox({button: true, quitOnDocClick: true, navigation: false, arrows: true, overlay: true, caption: true});
$('a[data-imagelightbox="dreifeld"]').imageLightbox({button: true, quitOnDocClick: true, navigation: false, arrows: true, overlay: true, caption: true});
$('a[data-imagelightbox="delle"]').imageLightbox({button: true, quitOnDocClick: true, navigation: false, arrows: true, overlay: true, caption: true});
 });</script>`
is present

**Comment by rejas** [comment]
So did you change all lines of "quitOnDocClick: true," to false?

**Comment by mspann** [comment]
Yes i did. Sorry, had the old version in the clipboard.
I also tried replacing `$(function() {` with `$(document).ready(function() {` but that also didn't change anything. Do I need to use any other lines of code when using Imagelightbox? Because the lightbox itself works flawless - just not the combination of my bootstrap collapsed nav menu and imagelightbox.

**Comment by rejas** [comment]
No, you shouldnt need any other lines of code. Could you try another config:

.imageLightbox({button: true, quitOnDocClick: false}); 

for all 3 galleries and see if it then works?

Also I see a googlemap error on your page, that probably doesnt have to do with this issue but nevertheless should be fixed to be sure.

**Comment by mspann** [comment]
Just to make sure, I've removed the google map for now. Tried the config above and unfortunately doesn't work.

**Comment by rejas** [comment]
Strange strange, but at least I have some (non-)working example set up at my computer where I can take a better look now. Can't guarantee tthough that I get it fixed today.

**Comment by mspann** [comment]
If you need anything from me let me know! I appreciate the support!

**Comment by rejas** [comment]
Published v0.7.1 in the npm-registry, should fix your problems :-)
