### ISSUE TITLE
$(document).off('click', options.selector) affects other 3rd libraries.

### ISSUE THREAD

**Issue by komenixx** [rejas/imagelightbox#114]
https://github.com/rejas/imagelightbox/blob/master/src/imagelightbox.js#L561

**Comment by rejas** [comment]
could you specify the affected libraries and what sideeffects happen?

**Comment by komenixx** [comment]
For example, affects the bootstrap click events. For example navbar

**Comment by rejas** [comment]
I fixed an issue with bootstraps navbar (and probably other click events on the document selector) with yesterays release 0.7.1 Did you try that one out? And if it still persists, is there a live site I can see the bug in action?

**Comment by komenixx** [comment]
Aaaaaah... I checked latest release yesterday maybe hour before than you publish 0.7.1

In 0.7.1 works. Thanks
