### ISSUE TITLE
Easy way to disable on small screens?

### ISSUE THREAD

**Issue by paul-frost** [rejas/imagelightbox#120]
In my case the thumbnail images of 300px are already filling a phone screen, so the popup function is no advantage and probably a worse user experience.

**Comment by rejas** [comment]
The only immediate solution that comes to my mind is to not initialize the lightbox library when the screen is too small. That can be handled by your code that calls the imagelightbox. Know how to do it?

**Comment by paul-frost** [comment]
I could do with some help on that. I've never managed to get my head around javascript apart from making modifications to existing code.

**Comment by paul-frost** [comment]
I have a seperate JS file with a few jQuery bits in and have added this, which seems to work.

```
$(document).ready(function() {
    if ( $(window).width() > 600) {
        $( function() {
            $( '.lightBox a' ).imageLightbox();
        });
    }
});
```

**Comment by rejas** [comment]
Nice to hear that.
