### ISSUE TITLE
Possibility to add 'onLoadEnd' hook  (when popup has completely loaded.)

### ISSUE THREAD

**Issue by RyanGosden** [rejas/imagelightbox#126]
Possibility to add 'onLoadEnd' hook similar to original repo. 

I ran into the issue where I wanted to obtain width, height and position attributes of popup element ('#archive_lightbox') in order to add an overlay. Although when using 'loaded.ilb2', the element had not been created yet, leading to an undefined.

**Comment by rejas** [comment]
Thx for the bug report, I moved the event trigger back to when the element is really loaded so that you wont get an undefined anymore

**Comment by RyanGosden** [comment]
@rejas - Great stuff - thank you for the fast response.
