### ISSUE TITLE
How can I align the image center of the screen?

### ISSUE THREAD

**Issue by AriosChief** [rejas/imagelightbox#128]
Hello!
I was hoping there is a standard way to do this, without hooks
So, how?

**Comment by rejas** [comment]
It should be centered by default. So maybe you experience a bug? Anyway, a little more explanation about your situation would help a lot. 
Thx in advance

**Comment by AriosChief** [comment]
I meant to center vertically.
I'm sorry that I did not immediately written.

**Comment by AriosChief** [comment]
If the picture with a small height that it sticks to the top
http://joxi.ru/l2ZL8JEH8wopXr - screenshot. I replaced the picture of the example.

**Comment by rejas** [comment]
Ah, i see. I will look into it (maybe tomorrow)

**Comment by rejas** [comment]
I do have a fix for it locally (check the issue_128-branch out), but it would disabled for now the gutter and offsetY options. Not sure if they are needed anymore. Hopefully @paxperscientiam can weigh in why they are needed?

**Comment by moxdev** [comment]
Experiencing the same exact issue. No matter what size the image is pinned to the top of the browser 15px from the top. Was not using the gutter or offsetY options. Below are the options I used:

`activity: true,
arrows: true,
button:true,
lockbody:true,
overlay:true,
preloadNext: true`

Same issue in version 7.6 and 7.5 scripts. Reverting back to version 7.2 seems to have resolved the issue.

**Comment by rejas** [comment]
Yeah, after 7.2 the positioning of the image changed. But did you try the "issue_128"-branch to see if my pending changes there fixes it for you?

**Comment by paxperscientiam** [comment]
@rejas I'll take a looky

**Comment by Phoca** [comment]
Hi everyone,
I just encountered the same problem. The bug occurs when full size images with different resolutions are used. It looks to me that the popup is centered to the size of the first element, images with other resolutions stick to the top.
I created a [fiddle to demonstrate it](https://jsfiddle.net/cxbbeLkn/3/).

**Comment by rejas** [comment]
I just released v0.7.9 which should fix the positioning

**Comment by Phoca** [comment]
thank you, works for me now 👍
