### ISSUE TITLE
Styling entry a la webpack

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#131]
This is a reminder for @paxperscientiam

**Comment by rejas** [comment]
Pinging @paxperscientiam: Can you elaborate or can I close this?

**Comment by paxperscientiam** [comment]
I think you should close @rejas. I don't know when I'll be able to think
about it :/

**Comment by rejas** [comment]
Still curious what you mean with that. We do have a style entry in package.json already, or what do you mean?

**Comment by paxperscientiam** [comment]
IIRC, it had something to do with webpack. I added a script entry point or
something for webpack a while back.

**Comment by rejas** [comment]
Well, already have a main entry in package.json, works in my webpack project, so yeah, closing this....
