### ISSUE TITLE
Search form doesn't work in combination with imagelightbox

### ISSUE THREAD

**Issue by Livingboy** [rejas/imagelightbox#134]
Hi guys,

I found a problem with imagelightbox in combination with the search form.
I'm using the imagelightbox on several subpages and on each of them the search form doesn't work if I hit enter. The lightbox works great on each page, but hitting the enter button on the keyboard doesn't redirect to the search page.
Am I the only one with that issue? How can it be solved?

Search form:
```
<form class="searchform" method="get" action="/">
<input type="text" placeholder="🔍 Search" class="s field" name="s">
</form>
```

My modifications:
```
<script type="text/javascript">
$(document).ready(function() {
    $('a[data-imagelightbox="a"]').imageLightbox({
        activity: true,
        arrows: true,
        button: true,
        navigation: true,
        overlay: true
    });
});
</script>
```

Lightbox links:
`<a href="https://domain.com/url_to_image.png" data-imagelightbox="a"><img src="https://domain.com/url_to_fullsize_image.png" alt="image description"></a>`

Best regards, Benjamin

**Comment by Livingboy** [comment]
Hi guys,

After some research and analyzing the source code I found out, that the following lines cause the issue:

$(document).on('keydown.ilb7', function (e) {
     if ([13].indexOf(e.which) > -1) {
         e.preventDefault();
     }
});

Best, Benjamin

**Comment by rejas** [comment]
Hi Benjamin, yes this is a know issue already, see issue #133 If you want you can try out the branch "issue_133" to see if it fixes your problem (and doesnt introduce new ones :-)
