### ISSUE TITLE
Image slide animations go the wrong directions!

### ISSUE THREAD

**Issue by beneklisefski** [rejas/imagelightbox#136]
This (bug?) is visible on the demo page as well as on my own implementation. When I go to the "next" image I would expect that image to slide in from the right side (right to left), and when going to previous image it should slide in left to right. However this plugin appears to slide images in from the reverse direction expected. How can I switch this direction?

It's especially awkward on touch devices, when you slide an image to the left to go to next image, but then instead of the next image coming in from the right, it comes back in from the left, which is super awkward and un-intuitive.

Please let me know how this can be solved.

**Comment by rejas** [comment]
You are right, that is counter-intiutive. Luckily its just a few lines to change.
