### ISSUE TITLE
JSFiddle example not works with current version of imagelightbox

### ISSUE THREAD

**Issue by LukasSliacky** [rejas/imagelightbox#137]
Hi,
i use your great Image Lightbox in my web project, but i have problem with "Multiple sets",
Example in jsfiddle works fine (Linux: Firefox, Chromium), but when i try it on Win Chrome {v64.0.3282.167 (64-bits)), i have this problem:

After click on image (maximize img) and move with mouse cursor, image is fast move out of window.

When i try use current version of lib (copy & paste) on begin of js file, example not works.

Thank you for any ideas.

**Comment by rejas** [comment]
Yeah, that example seems way out of date, didnt look at it for ages.

**Comment by rejas** [comment]
Works on my chrome, closing this issue for now
