### ISSUE TITLE
Change http to https (website demo CSS error)

### ISSUE THREAD

**Issue by eladkarako** [rejas/imagelightbox#138]
in <code>https://rejas.github.io/imagelightbox/stylesheets/demo.css</code>
change the <code>@import url('http://fonts.googleapis.</code> to <code>@import url('//fonts.googleapis.</code>

<sub><em>(or better yet, since it isn't your CDN: <code>@import url('<strong>https</strong>://fonts.googleapis.</strong></code> so it will work on IE too...)</em></sub>

<img src="https://i.imgur.com/ZeV1DM1l.png"/>

**Comment by rejas** [comment]
Thx for the hint, much appreciated!
