### ISSUE TITLE
allowedTypes validation breaks images without extension

### ISSUE THREAD

**Issue by GenaBitu** [rejas/imagelightbox#141]
When loading images that do not have an extension (e. g. from a third party service), the function `isTargetValid` effectively breaks the gallery because most images are discarded. Currently I see no way to turn this off as the `allowedTypes` is checked so `.*` cannot be put there.

**Comment by rejas** [comment]
Yeah, that feature has rotten something sicne the reworks. Will take a look later at it, has to be fixed anyway :-)

**Comment by GenaBitu** [comment]
To put my two cents in - is such a feature even useful? I can't imagine a situation where I would like to filter by file type - if I'd want to add the lightbox to some images only, I would do that with the `data-imagelightbox` argument...

**Comment by rejas** [comment]
Well, the feature was in the original authors code so I didnt remove it (the usefulness is indeed questionable). You can check out v0.9.0 where you could use the emptry string as the parameter for allowedTypes to make it work with any files. Please report any errors I made :-D

**Comment by GenaBitu** [comment]
Works like a charm, thank you very much for the amazing work you've done on this package to get it to be more usable than the original.

**Comment by rejas** [comment]
always happy to help but most of the work was done by @osvaldasvalutis and @paxperscientiam :-) might i ask if are you using the package in a real-life project which we could mention here?

**Comment by GenaBitu** [comment]
I am making a WordPress plugin which makes galleries out of Google Drive folders - feel free to check it out at https://github.com/skaut/skaut-google-drive-gallery (some of it is in czech but not much). I am using imagelightbox for the galleries as it seems to be a good middle ground between usable and not bloated...

**Comment by paxperscientiam** [comment]
I don't remember the original intention, but I had always seen it as a very simple extension-based filter for dynamically generated galleries.

It would / could *not* serve as validation.

**Comment by GenaBitu** [comment]
I only now got around to making a demo page for the plugin: https://demo-skaut-google-drive-gallery.skauting.cz - There is an example of a simple gallery and a galllery with subdirectories - both using imagelightbox.
Also, I've written some info about what the plugin actually does over here: https://wordpress.org/plugins/skaut-google-drive-gallery/
