### ISSUE TITLE
anchors stop working after initializing imagelightbox

### ISSUE THREAD

**Issue by jmslbam** [rejas/imagelightbox#18]

**Comment by rejas** [comment]
could you provide a link to your code where this happens?

**Comment by jmslbam** [comment]
http://noordkade34.nl/

You can even check the code here https://github.com/noordkade34/noordkade34.github.io

**Comment by jmslbam** [comment]
I use CodeKit to build everything and `python -m SimpleHTTPServer 8000 ` on my mac to run a simple webserver.

**Comment by jmslbam** [comment]
When I refresh the page with the anchor it does jump, but the click just seems to be disapeared

**Comment by rejas** [comment]
And when you dont initliaze the imageboxes it works?

**Comment by jmslbam** [comment]
yupp

**Comment by jmslbam** [comment]
All the links seem to stop working. also the `mailto` and `phone` ones.

btw I'm on OSX 10.9.2 and Latest FF and Chrome

**Comment by rejas** [comment]
Strange indeed... Will take a look later today, hope you can wait :-)

**Comment by jmslbam** [comment]
yupp, can wait, am debug-in it also. thanks btw!

**Comment by jmslbam** [comment]
Ok found it, settings `quitOnDocClick: true` fixes it. So going with that one for now.

**Comment by jmslbam** [comment]
It's this one https://github.com/rejas/imagelightbox/blob/master/src/imagelightbox.js#L319

Don't know why we wanted to prevent the default event of an the click on the `document`, you have a clue?

**Comment by rejas** [comment]
think i found the issue, we should only prevent the event if the click happens when the lightbox is opened. can you confirm this fixes your problem?
