### ISSUE TITLE
Suggestion: Allow pinch-zooming on touch devices

### ISSUE THREAD

**Issue by robaxx** [rejas/imagelightbox#186]
The suggestion is to allow the user to use the pinch-to-zoom feature to zoom in on the lightbox image. 
Some lightbox scripts allow this, but this one doesn't. I'm unsure what exactly stops it zooming, but it must be something in the script.

**Comment by rejas** [comment]
hi @robaxx similar to https://github.com/rejas/imagelightbox/issues/36 I wouldnt know how to do this without adding another dependency. Could you maybe give an example of anothe rlightbox that handles this without a third party library?

**Comment by rejas** [comment]
Closing this in favor of https://github.com/rejas/imagelightbox/issues/36
