### ISSUE TITLE
Clicking the image/video itself always navigates to previous image/video

### ISSUE THREAD

**Issue by leffi7** [rejas/imagelightbox#193]
Hi,

I am using Chrome version 73.0.3683.86 (Officiële build) (64-bits)

When I click an image itself, it navigates to the previous image. I noticed the same behaviour on the demo page: http://rejas.github.io/imagelightbox/
image 1 goes to image 3, image 3 to image 2, ...

This might be a little confusing:
1. Shouldn't you navigate to the next image: 1 to 2, 2 to 3, etc...
2. Especially when using video's, since users are used to click in the center of a video to start playing.

Is there a way to disable this behaviour so the user can only navigate by using the next-previous buttons? Couldn't find it as an option.

Thank you!

**Comment by GenaBitu** [comment]
Hi,
oh, this is not the intended behaviour at all, it should obviously go to the next one... And in case ogf the video, it should play it, which it does on FF (my browser of choice), but apparently not in Chrome.
Thanks for spotting this, this is a bug.

**Comment by rejas** [comment]
For the prev/next issue I have an idea why it happens.

**Comment by GenaBitu** [comment]
My (first) idea for the video issue is:
The video should play on click, but it should also move to the next image. This means that there are two events listening for a click. And different browsers prefer different events.

If this is the case, that would mean that we should only add the onclick scroll to images, not videos.

**Comment by leffi7** [comment]
An additional issue: I noticed the video controls aren't working at all on Safari. Firefox and Chrome are OK.

Hope this helps somehow.

Thx!!

**Comment by GenaBitu** [comment]
Hi,
I think I fixed the video part in #195 - it works at least in my Chromium...
@leffi7 Could you please check it in Safari?

Thanks...

**Comment by leffi7** [comment]
Works perfect! I checked in Chrome, Safari and Firefox.

Very nice!

Thank you!!

**Comment by GenaBitu** [comment]
Great. I have one more change to make and then could we make it a new release, @rejas?
