### ISSUE TITLE
Is there any way to show images from data-images="" property?

### ISSUE THREAD

**Issue by fatihturan** [rejas/imagelightbox#24]
Hi,

Is there any way to show all images from data-images=“” property? Like a lightbox gallery will work from data-images="/img1.jpg,img2.jpg,img3.jpg"... 

By the way I did it before with MagnificPopup plugin on my old web site ([you can check this example page](http://fatihturan.com/calismalarim/) also [code snippet](http://pastie.org/10651117)). But I want to accomplish this feature with this Imagelightbox plugin.

Thanks.

**Comment by THenkeDE** [comment]
Maybe this can help you out. Not the "best practice" i guess but it helped me once:

<a id="myBox1" href="img1.png" data-lightbox-images="img2.png,img3.png,img4.png">Start the Show</a>

	<script language="Javascript">
		$(document).ready(function() {
			var myImages = $('#myBox1').data('lightbox-images').split(',');
			if( myImages.length > 0 ) {
		        var gallery = $('#myBox1').imageLightbox();
				for( var i = 0; i < myImages.length; i++ ){
					gallery.addImageLightbox( $('<div data-lightbox="'+myImages[i]+'" />') );
		        }
			}
		});
	</script>

The <a> Tag will have to have the first image if your slide as href and then the other images as data-tag ...

**Comment by fatihturan** [comment]
Unfortunately, it didn't work for me (or I can't run this example). Can you give me your example under the Jsfiddle or Jsbin?

**Comment by THenkeDE** [comment]
my example is in a backend but if you can setup your test as a fiddle we could all have a look
