### ISSUE TITLE
Lightbox bugs out with captions if any images lack "alt" attribute.

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#25]
It's all there in the comments, though I'm unsure if it's also caused by an interaction with other functions. Basically, if any image is missing the "alt" attribute, the images will begin to "stack" as you move from one to the next.

EDIT: The above does NOT happen if the image has an empty alt attribute; however, the caption text persists rather than be replaced with an empty caption.

**Comment by rejas** [comment]
Thanks for the report, I can reproduce it, will look into it.
