### ISSUE TITLE
Minor interesting bug

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#28]
Hi there @rejas 

While working on the fork, I discovered an interesting bug that causes "alt" values to be recycled when reusing image links despite unique alt values. To clarify, I'm referring to the "href" values from "<a>" and not the "src" values from "<img>".

Here's a minimal example:
```HTML
<div class="column" >
      <a href="http://placehold.it/500x300" data-imagelightbox="LD">
       <img src="http://placehold.it/500x300" class="center-light thumbnail" alt="Hi" />
      </a>
     </div>
     <div class="column" >
      <a href="http://placehold.it/500x300" data-imagelightbox="LD">
       <img src="http://placehold.it/500x300" class="center-light thumbnail" alt="Bye" />
      </a>
     </div>
 <div class="column" >
      <a href="http://placehold.it/500x300" data-imagelightbox="LD">
       <img src="http://placehold.it/500x300" class="center-light thumbnail" alt="Hello" />
      </a>
     </div>
````

As you've likely surmised, this bug is relevant to the creation of HTML templates where it is typical to link to the same image file multiple times. I'm assuming it doesn't matter if the image file is server local or remote (as above).

The simple gallery above should -- with captions on and assuming you click on the first image -- display "Hi", "Hi", and "Hello" for each image, respectively.

**Comment by rejas** [comment]
Hi @paxperscientiam sorry for answering so late.

Seems like this bug only appears of the img src of the a-tags are the same? Can you confirm that?

**Comment by paxperscientiam** [comment]
G'ah, wow, I'm late to respond!

> Seems like this bug only appears of the img src of the a-tags are the same?

No, it doesn't seem to matter how much "src" values are repeated. It happens only when "href" values are repeated.

**Comment by rejas** [comment]
You're right. I fixed in the development branch. Or do you need it in the master?

**Comment by paxperscientiam** [comment]
Cool. Nah, I don't need it in master. Where do we stand on the PR?
