### ISSUE TITLE
Multiple Instances?

### ISSUE THREAD

**Issue by ritualgym** [rejas/imagelightbox#34]
I cannot safely "destroy" the plugin if i am trying to use it and it gets called multiple times?  It will append "n" number of plugins depending on how many times it has been initialised.  Can we make it that only one instance of the plugin can run for any single selector?

e.g. 
var selectorF = 'a[data-imagelightbox="f"]';  
        var instanceF = $(selectorF).imageLightbox();

Calling this twice would only setup one instance...maybe destory the previous one would be useful or have / follow a "destroy" model ?

thanks for the fork :)

**Comment by rejas** [comment]
Weird, I thought I already responded to this issue... Well, anyway.... Since I hadnt had that usecase of multiple isntance or having to destroy the imagelightbox, I didnt bother about it. Did you already code it for yourself? Always happy for pull requests ;-)

**Comment by paxperscientiam** [comment]
In my retooling, i use a div wrapper for the ILB elements. Quitting ILB causes those nested components to be destroyed.

I think in order to allow multiple groups (instances based on different class selectors), event handling has to be namespaced.

**Comment by paxperscientiam** [comment]
@ritualgym, see latest release.

**Comment by rejas** [comment]
Closing since multiple instances should work for several releases already. Please open a new ticket if something is still wrong..
