### ISSUE TITLE
Remove fading from captions

### ISSUE THREAD

**Issue by rejas** [rejas/imagelightbox#35]
From "paxperscientiam": I don't think captions should fade away when switching from image to the next: it seems like an unnecessary distraction. If instead the caption box remained when changing over images, I think it would be better.

**Comment by paxperscientiam** [comment]
OK, think I've figured this one out, but more testing is needed. Also, it'll be part of an omnibus PR.

**Comment by paxperscientiam** [comment]
This can be closed. See PR #58
