### ISSUE TITLE
Add DeepLinking functionality

### ISSUE THREAD

**Issue by rejas** [rejas/imagelightbox#37]
From "paxperscientiam": I actually started tinkering with deeplinking (linking to image X so that the imagebox opens directly with it) and it's going well so far. I hope to put up a rough draft soon. You can expect something on this end.

**Comment by Art4** [comment]
I was able to do exactly this thing with version 0.5.4:

```js
// location: http://example.org/galleries/123#showImage_34
var hashData = $(location).attr('hash').substring(1).split('_');

if (hashData.length > 0 && hashData[0] == 'showImage')
{
	// start imagelightbox with this image
	var image = $('.lightbox span[data-image-id="' + hashData[1] + '"]');
	var lightboxInstance = image.imageLightbox(imagelightbox_options);
	// add all other images to this instance
	var images = $('.lightbox span[data-image-id]').each(function() {
		// but only if it wasn't the first image
		if (image.data('image-id') != $(this).data('image-id')) {
			lightboxInstance.addToImageLightbox( $(this) );
		}
	});
	lightboxInstance.startImageLightbox();
}
else
{
	var lightboxInstance = $('.lightbox span').imageLightbox(imagelightbox_options);
}
```

Unfortunately this don't work anymore if I updated to 0.7.2 or higher, because of the refactoring for the fullscreen feature.

**Comment by rejas** [comment]
I updated the code to allow deep linking and added an example on how to achieve it now. Thanks for your code!
