### ISSUE TITLE
images are not vertically centered - landscape mode, Chrome, iPhone 4

### ISSUE THREAD

**Issue by jendabek** [rejas/imagelightbox#4]

**Comment by rejas** [comment]
could you provide a screenshot since i dont have an iphone?

**Comment by hanwiz** [comment]
This should be related to a issue of height problem in iOS. Here is a workaround for this.

var screenWidth = $(window).width() * 0.8,
                    wHeight = (window.innerHeight) ? window.innerHeight : $(window).height(),                    
                    screenHeight = wHeight * 0.9,
                    tmpImage = new Image();

                tmpImage.src = image.attr('src');
                tmpImage.onload = function () {
                    imageWidth = tmpImage.width;
                    imageHeight = tmpImage.height;

                    if (imageWidth > screenWidth || imageHeight > screenHeight) {
                        var ratio = imageWidth / imageHeight > screenWidth / screenHeight ? imageWidth / screenWidth : imageHeight / screenHeight;
                        imageWidth /= ratio;
                        imageWidth = Math.floor(imageWidth);
                        imageHeight /= ratio;
                        imageHeight = Math.floor(imageHeight);
                    }

                    image.css({
                        'width': imageWidth + 'px',
                        'height': imageHeight + 'px',
                        'top': ( wHeight - imageHeight ) / 2 + 'px',
                        'left': ( $(window).width() - imageWidth ) / 2 + 'px'
                    });
                };

**Comment by rejas** [comment]
Is this still an issue with the latest ios release? And if so, might you be itnerested in doing a pull request for the fix?

**Comment by rejas** [comment]
fixed via https://github.com/rejas/imagelightbox/commit/e39a42ba968efd45be13a25bd0e996bf3b71b252
