### ISSUE TITLE
startImageLightbox is broken in v0.5.0

### ISSUE THREAD

**Issue by rejas** [rejas/imagelightbox#42]

**Comment by masiorama** [comment]
Still broken on 0.5.1 as for the minified version on dist directory. The not minified inside the src folder works.

**Comment by rejas** [comment]
Might have forgotten to update that dist file last time :-) Could you re-test with v0.5.2 ?

**Comment by masiorama** [comment]
Sure, no problem. Already updated? I still see the old dist directory...

**Comment by rejas** [comment]
How you you install the project? Via bower or npm?

**Comment by masiorama** [comment]
Bower

**Comment by masiorama** [comment]
Now it works perfectly, thanks. :+1:

**Comment by rejas** [comment]
Awesome. Have a nice day.
