### ISSUE TITLE
Add less/sass support

### ISSUE THREAD

**Issue by masiorama** [rejas/imagelightbox#48]
It would be nice to also have less and/or sass version of the stylesheet for those who work primarly with preprocessors rather than plain css.

**Comment by rejas** [comment]
I mainly work with less as a preprocessor so I cannot speak for the sass-side of things. So in less I would import the stylesheet css and overwrite anything that doesnt fit my design. Where would less be of any help there? The main primary goal is having a minimal css that is easily overwritten (by not having a high specifity that prevents it) So if there are css classes that are too heavy, would be an issue that needs to be fixed. Or where are other immediate benefits of writing in less/sass and then compiling into a dist-imagelightbox.min.css?

**Comment by masiorama** [comment]
From what you've written I dig more in less options and find out that this
`@import (css) "foo.css";`
actually accomplish what I needed. I wasn't aware of import options features.
As you said the css is really minimal and I cannot find any reason to pack your dist with less/sass version of the css. You can close, thank you very much! :-)

**Comment by rejas** [comment]
Glad I could help with the import feature. But I didnt want to discourage you if you wanted to convert the css into less (and submit a PR), I just thought for me I couldnt find the time for it. The css needs a little cleanup anyway, so why not convert it in less (if you really want to help ;-)

**Comment by paxperscientiam** [comment]
@rejas Do you still use Less? I use Scss and I was just wondering about providing both the source file and the dist file.

**Comment by rejas** [comment]
Yeah, I'd say too that the need for less/sass isnt really there. A simple css with low specifity is fine.
