### ISSUE TITLE
Fix demos after imagelightbox sets merge

### ISSUE THREAD

**Issue by rejas** [rejas/imagelightbox#63]
The "dynamically adding" and "with manual trigger" examples dont work correctly anymore after merging https://github.com/rejas/imagelightbox/pull/62 :-(

**Comment by rejas** [comment]
@paxperscientiam those features still need to be fixed before any new release can be done, are you on it?

**Comment by paxperscientiam** [comment]
@rejas examining

**Comment by rejas** [comment]
thx for the fix of the manual trigger, dynamic add is still broken though.
not sure why your tests dont fail. to see the bug manully, add the image and click on it and then on the nav button

**Comment by paxperscientiam** [comment]
> add the image and click on it and then on the next arrow

Ah. See you at the new PR.

**Comment by rejas** [comment]
thx again!

**Comment by paxperscientiam** [comment]
You're welcome :)
