### ISSUE TITLE
Incorrect nav element counting on some user-agents

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#73]
This was reported by a client using iOS and Chrome on OSX.

It seems that in certain cases, the nav elements are double counted. This might be related to a counter not being reset or something not being properly destroyed.

**Comment by rejas** [comment]
"Certain cases" means every time or only sometimes?

**Comment by paxperscientiam** [comment]
@rejas OK, nevermind, client (read:I) was mistaken.
