### ISSUE TITLE
questions about testing suite

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#75]
Hi @rejas 

I think the testing server is really cool and useful. There are a few minor issues though.

* Can you set the index page so that it only shows files/dirs meant to be tested? If you check out [this](https://www.dropbox.com/s/ru5by3zeztiiyv2/Screenshot%202016-12-01%2001.12.04.png?dl=0) screenshot, you'll see that a lot of cruft winds up getting listed.
* Not sure if this should be handled by you, but is there something you can do so that changes to the dist/ directory do not clog up `git diff` results?

# EDIT
Maybe webroot should just be the docs directory?

**Comment by rejas** [comment]
- Sorry, can't see the screenshot, dropbox claims it's still uplaoding :-)
- Not sure if that can be supressed in the git diff, but adding the dist to the ignore is the wrong approach, sorry.

**Comment by paxperscientiam** [comment]
Ug, my dropbox is playing catch up. Sorry.

OK, I had a feeling that that was a collaborator-side issue.

Does the gulpfile not automatically open a browser tab by default? Also, live refresh is not working for me.

**Comment by rejas** [comment]
Didn't look at livereloading there yet to be honest. How do you want to use it there?

**Comment by paxperscientiam** [comment]
I believe edits to "src/*" triggers a build of production files, which are sent to "dist/". In addition, it looks like a copy "src/imagelightbox.css" and "src/imagelightbox.js" are sent to "docs/stylesheets/" and "docs/javascripts/", respectively.

With that all laid out there, I'd say that changes to "docs/stylesheets/*", "docs/javascripts/", and "docs/index.html" should trigger a refresh. This will save time on testing moving forward.

For live building, I use BrowserSync, which will open tabs in all open browsers in desired. I'm not familiar with your employed server, but it might just need tweaking to work with other browsers. Higher priority is refreshing as it's not so horrible to manually open a new tab.

**Comment by rejas** [comment]
You are right with your observation in paragraph1. The docs get an extra copy since they are used for the github.io page as well as for the tests. 
Question: How many times do you edit the files in the docs-dir? Updated the demo page shouldn happen too often and the tests (unless I screw something up) are somewhere else anyway.

**Comment by paxperscientiam** [comment]
Hey @rejas 

> How many times do you edit the files in the docs-dir?

As much as necessary, no? My understanding is that the demo source doubles as testing materials for repo contributors. At least, that's how I've been using it.

**Comment by rejas** [comment]
Yes, they double :-) Any more questions?
