### ISSUE TITLE
feature request: dynamically generated imagelightbox

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#78]
To extend the dynamic image addition concept, allow for provision of an image directory that can be used for dynamically generating imagelightbox sets. This is where extension filter would come in handy.

This would be for...like... v1.0?

**Comment by rejas** [comment]
To be honest, I dont see this as a feature for a frontend library. 
To get it working it would have to depend on an api in the backend to get the data, update the html and run its code itself. All while the page loads, which would lead to a lot of time passing until the lightbox gets displayed. If someone really wants to do it he can call the "dynamic add" mutliple times from his code.

**Comment by paxperscientiam** [comment]
>  If someone really wants to do it he can call the "dynamic add" mutliple times...

The difference here is that the problem of dynamically adding unknown images requires a programmatic solution. Sure, for a directory that will only ever have a handful of images, this is overkill. For a directory with with hundreds of images, different story.

> ...in the backend to get the data...

Yeah, this is ideal. I myself use PHP to dynamically create image links.

While possibly solveable with some Ajax-y stuff, it probably is beyond the scope of this project. What do you think?

**Comment by rejas** [comment]
Yeah, still not convinced that this is really needed, feasible or in the scope of this project. However it would be implkemented it would add a lot of code for a rarely used feature. And the feature can still be implemented outside of this library in other javascript. Sorry, have to pass on this idea.
