### ISSUE TITLE
Extend overlay effects?

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#90]
Extending is more work and probably beyond scope; however, I like the idea of improving the aesthetic of the overlay with a soft blur.

What do you think?

Here's a [WIP](https://github.com/paxperscientiam/imagelightbox/tree/improved-background-effects).

**Comment by rejas** [comment]
I dont think this should be part of a library. The default css should be as small as possible and the user be able to add his own stuff.
